# This is a basic workflow to help you get started with Actions

name: Test Event

on:
  workflow_dispatch:
    inputs:
      val1:
        description: 'value'     
        required: true
        default: 'one'
      val2:
        required: true
        default: 'two'
        description: 'input value'
        
  pull_request:
   branches: [ master ]       
   types: [labeled]
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: Send inputs
      run: echo "${{ github.event.inputs.val1 }} ${{ github.event.inputs.val2 }}" 
      
    - name: Send labels
      run: echo "${{ github.event.pull_request.labels }}" 
      
      
